# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

app-template:

  defaultPodOptions:
    labels: {}
    annotations:
      sidecar.istio.io/inject: "true"

  controllers:

    application:
      type: deployment
      replicas: 2

      labels: {}
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        main:
          image:
            repository: ghcr.io/freepik-company/prometheus-mcp
            tag: latest
            pullPolicy: Always

          args:
            - --config
            - /data/config.yaml

          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"

          envFrom: []
            # Uncomment this if the related section is enabled in 'rawResources'
            #- secretRef:
            #    name: "{{ .Release.Name }}-credentials"

  configMaps:
    configuration:
      enabled: true
      annotations: {}
      data:
        config.yaml: |
          # MCP Server Configuration
          server:
            name: "Prometheus MCP"
            version: "0.1.0"
            transport:
              type: "http"
              http:
                host: ":8080"
          
          # Middleware Configuration
          middleware:
          
            access_logs:
              excluded_headers:
                - X-Excluded
              redacted_headers:
                - Authorization
                - X-Validated-Jwt
        
            jwt:
              enabled: false
              validation:
                strategy: "external"  # Values: 'local' or 'external'
                # JWT forwarded by upstream proxy (Istio, etc.)
                # Ref: https://istio.io/latest/docs/reference/config/security/request_authentication/#JWTRule-output_payload_to_header
                forwarded_header: "X-Validated-Jwt"
                local:
                  jwks_uri: &JwksUri "https://keycloak.example.com/realms/mcp-servers/protocol/openid-connect/certs"
                  cache_interval: "10s"
          
                  # CEL expressions to fine tune allowance. JWT payload is available under object 'payload'
                  allow_conditions: []
                    #- expression: 'payload.groups.exists(group, group in ["admin", "editor"])'
                    #- expression: 'has(payload.email) && payload.email.endsWith("@example.com")'
          
          # Oauth Authorization Server Configuration
          # Endpoint: /.well-known/oauth-authorization-server
          oauth_authorization_server:
            enabled: true
          
            # Following path will be attached: /.well-known/openid-configuration
            issuer_uri: "https://keycloak.example.com/realms/mcp-servers"
    
          # OAuth Protected Resource Configuration
          # Endpoint: /.well-known/oauth-protected-resource
          oauth_protected_resource:
            enabled: true
            resource: "https://prometheus-mcp.example.com"
            auth_servers:
              - "https://keycloak.example.com/realms/mcp-servers"
            jwks_uri: *JwksUri
            scopes_supported:
              - openid
              - profile
              - email
              - groups
              - prometheus-mcp/custom-audience
          
            # Optional parameters (currently empty)
            bearer_methods_supported: []
            resource_signing_alg_values_supported: []
            resource_name: ""
            resource_documentation: ""
            resource_policy_uri: ""
            resource_tos_uri: ""
            tls_client_certificate_bound_access_tokens: false
            authorization_details_types_supported: []
            dpop_signing_alg_values_supported: []
            dpop_bound_access_tokens_required: false

  persistence:
    configuration:
      enabled: true
      name: "{{ .Release.Name }}"
      type: configMap
      advancedMounts:
        application: # Controller
          main: # Container
            - path: /data/config.yaml
              readOnly: true
              mountPropagation: None
              subPath: config.yaml

  service:
    backend:
      controller: application
      type: ClusterIP
      ports:
        http:
          port: 8080
          protocol: TCP

  # Some stuff is not covered by this chart
  rawResources:
    credentials:
      enabled: false
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      spec:
        spec:
          refreshInterval: "15s"
          secretStoreRef:
            name: external-secrets-hashicorp-vault
            kind: ClusterSecretStore
          target:
            name: "{{ .Release.Name }}-credentials"
          data:
            - secretKey: PLACEHOLDER
              remoteRef:
                key: your-kv/applications/prometheus-mcp/credentials
                property: username

    public-api-entrance:
      enabled: false
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      spec:
        spec:
          hostnames:
            - prometheus-mcp.example.com
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: production
              namespace: istio
              sectionName: https-terminate
          rules:
            - backendRefs: &mainBackendRef
                - group: ""
                  kind: Service
                  name: prometheus-mcp
                  port: 8080
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /

    # This is temporary here as a trick to preserve real-client-ip. The ideal solution is trusting CIDRs, but it requires
    # Istio be able to set 'use_remote_address: false' and ATM, it's hardcoded for the gateways:
    # Ref: https://github.com/istio/istio/blob/f772ceea87ae58896e1eabe2cf83ebfd8c54bf6d/pilot/pkg/networking/core/v1alpha3/gateway.go#L358
    preserve-client-ip:
      enabled: false
      apiVersion: networking.istio.io/v1alpha3
      kind: EnvoyFilter
      spec:
        spec:
          workloadSelector:
            labels:
              app.kubernetes.io/name: prometheus-mcp
          configPatches:
            - applyTo: NETWORK_FILTER
              match:
                context: ANY
                listener:
                  filterChain:
                    filter:
                      name: envoy.filters.network.http_connection_manager
              patch:
                operation: MERGE
                value:
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    xff_num_trusted_hops: 3
                    use_remote_address: true
                    skip_xff_append: false

    istio-deny-access-from-untrusted-sources:
      enabled: false
      apiVersion: security.istio.io/v1
      kind: AuthorizationPolicy
      spec:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-mcp

          action: DENY
          rules:
            - from:
                - source:
                    notRemoteIpBlocks:
                      # Kubernetes stuff
                      - 10.0.0.0/8

                      # Claude Web GUI
                      - 34.162.102.82/32
                      - 34.162.183.95/32
                      - 34.162.142.92/32
                      - 34.162.46.92/32
                      - 34.162.136.91/32

                      # Other providers from here
                      # ...
              to:
                - operation:
                    paths:
                      - /
                      - /*

    istio-request-authentication-header:
      enabled: false
      apiVersion: security.istio.io/v1
      kind: RequestAuthentication
      spec:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-mcp
          jwtRules:
            - forwardOriginalToken: true
              outputPayloadToHeader: X-Validated-Jwt
              issuer: https://keycloak.example.com/realms/mcp-servers
              jwksUri: https://keycloak.example.com/realms/mcp-servers/protocol/openid-connect/certs

    istio-check-jwt-claims:
      enabled: false
      apiVersion: security.istio.io/v1
      kind: AuthorizationPolicy
      spec:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-mcp
          action: DENY
          rules:
            - to:
                - operation:
                    paths:
                      - /mcp
                      - /mcp/*
              when:
                - key: request.auth.claims[iss]
                  notValues:
                    - https://keycloak.example.com/realms/mcp-servers
                - key: request.auth.audiences
                  notValues:
                    - https://prometheus-mcp.example.com
